import type {
  Annotation,
  ConstantDef,
  EnumDef,
  EnumMember,
  Field,
  IrSchema,
  PluginOutputFile,
  Position,
  TypeDef,
  TypeKind,
  TypeRef,
} from "@varavel/vdl-plugin-sdk";

/**
 * Configuration options for the Go code generator.
 */
export interface GeneratorOptions {
  /** The name of the generated Go package. */
  packageName: string;
  /** Whether to generate Go constants for VDL constants. */
  genConsts: boolean;
  /** Whether to generate the metadata.go file. */
  genMeta: boolean;
  /** Whether to generate pointer utility helpers (Ptr, Val, Or). */
  genPointerUtils: boolean;
  /** Whether to generate strict JSON validation logic. */
  strict: boolean;
}

/** Represents a file generated by the plugin. */
export type GeneratedFile = PluginOutputFile;

/**
 * Describes a field within a Go struct.
 */
export interface FieldDescriptor {
  /** The original VDL field definition. */
  def: Field;
  /** The PascalCase Go name for the field. */
  goName: string;
  /** The exact JSON tag name. */
  jsonName: string;
  /** The rendered Go type string for the field. */
  goType: string;
  /** The Go name for the type if it is an inline object. */
  inlineTypeGoName: string;
}

/**
 * Describes a named Go type (struct or alias).
 */
export interface NamedTypeDescriptor {
  /** The PascalCase Go name of the type. */
  goName: string;
  /** The original VDL name. */
  vdlName: string;
  /** The internal path identifying the type. */
  path: string;
  /** Whether this type was defined inline within another object. */
  inline: boolean;
  /** The Go name of the containing type if this is an inline type. */
  parentGoName?: string;
  /** Documentation comment lines. */
  doc?: string;
  /** VDL annotations attached to this type. */
  annotations: Annotation[];
  /** Source position in the VDL file. */
  position: Position;
  /** The kind of type (e.g., "object", "primitive", "array"). */
  kind: TypeKind;
  /** The VDL type reference. */
  typeRef: TypeRef;
  /** Descriptors for all fields if this is an object/struct. */
  fields: FieldDescriptor[];
}

/**
 * Describes a single member of a Go enum.
 */
export interface EnumMemberDescriptor {
  /** The original VDL enum member definition. */
  def: EnumMember;
  /** The PascalCase Go name of the member. */
  goName: string;
  /** The full PascalCase Go constant name (usually <Enum><Member>). */
  constName: string;
  /** A stable hash key of the member value for lookups. */
  valueKey: string;
}

/**
 * Describes a Go enum type.
 */
export interface EnumDescriptor {
  /** The original VDL enum definition. */
  def: EnumDef;
  /** The PascalCase Go name of the enum type. */
  goName: string;
  /** The name of the generated slice containing all enum members. */
  listGoName: string;
  /** Ordered list of member descriptors. */
  members: EnumMemberDescriptor[];
  /** Lookup map for members by their hashed value key. */
  memberByValue: Map<string, EnumMemberDescriptor>;
}

/**
 * Describes a Go constant.
 */
export interface ConstantDescriptor {
  /** The original VDL constant definition. */
  def: ConstantDef;
  /** The PascalCase Go name of the constant. */
  goName: string;
  /** The VDL type reference for the constant. */
  typeRef: TypeRef;
}

/**
 * The unified context used throughout the generation stages.
 *
 * It contains all indexed schema data, derived Go names, and processed
 * descriptors for types, enums, and constants.
 */
export interface GeneratorContext {
  /** The full flattened VDL IR schema. */
  schema: IrSchema;
  /** The resolved generator options. */
  options: GeneratorOptions;
  /** Raw VDL type definitions indexed by name. */
  typeDefsByVdlName: Map<string, TypeDef>;
  /** Map of VDL type names to their final Go names. */
  typeGoNamesByVdlName: Map<string, string>;
  /** Map of VDL enum names to their final Go names. */
  enumGoNamesByVdlName: Map<string, string>;
  /** All processed named types (including inline ones). */
  namedTypes: NamedTypeDescriptor[];
  /** Lookup map for named types by their Go name. */
  namedTypesByGoName: Map<string, NamedTypeDescriptor>;
  /** All processed enums. */
  enumDescriptors: EnumDescriptor[];
  /** Lookup map for enums by their VDL name. */
  enumDescriptorsByVdlName: Map<string, EnumDescriptor>;
  /** All processed constants. */
  constantDescriptors: ConstantDescriptor[];
}
